### PR TITLE
Oracle compatibility

### PR DESCRIPTION
**Pull request by bardbess**
Renamed the last_authenticated_with_yubikey table column to be less than
30 characters long so that this gem is compadible with oracle databases

### CODE REVIEW

**Comment by dennisreimann** [comment]
Can you add a migration for that change instead of altering the schema? That way existing installations can be upgraded.

**Comment by kerrizor** [comment]
@bardbess I agree that the change should be in a migration. I'm not familiar at all with Oracle, so forgive what may seem naive, but will the current migrations run, given a <30 character restraint? IE - do we need to do anything fancier here, like alter earlier migrations, and then do some ```if/else``` in a new migration to retroactively alter the key if its the previous >30 character version?

**Comment by bardbess** [comment]
@kerrizor 30 characters is fine. That's the limit. I have run the migration in without any issues.

**Comment by dennisreimann** [comment]
@bardbess You can run the migartion just fine, because you changed the initial migration. My point was adding a new migration that changes the column name after all the previous migrations have been run.

Users that would want to upgrade to the latest version after this has been published would need the database changes too. Currently they would have to apply these changes manually because they have already run the migrations and would need a new one.

**Comment by bardbess** [comment]
I cant understand what I did to make the mysql2 tests fail. But sqlite3 pass fine. Migration for existing users has been added and amended. - appreciate your patience. This is really my first github pull request.

**Pull request closed without merging**
